<?php

/** Generated by Latte 3.0.23 */

use Latte\Runtime as LR;

/** source: E:\GitHub\SimonPortillo\soknadsystem_php\app\views\layout.latte */
final class Template_fa3143fdbd extends Latte\Runtime\Template
{
	public const Source = 'E:\\GitHub\\SimonPortillo\\soknadsystem_php\\app\\views\\layout.latte';

	public const Blocks = [
		['title' => 'blockTitle', 'styles' => 'blockStyles', 'navigation' => 'blockNavigation', 'scripts' => 'blockScripts'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>';
		$this->renderBlock('title', get_defined_vars()) /* line 6 */;
		echo '</title>
    
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    
';
		$this->renderBlock('styles', get_defined_vars()) /* line 11 */;
		echo '</head>
<body>
    <header class="bg-dark text-white mb-4">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="/">
                    <h1 class="h3 mb-0">FlightPHP Skeleton</h1>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
';
		$this->renderBlock('navigation', get_defined_vars()) /* line 25 */;
		echo '                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main class="container">
';
		if (isset($errors) && $errors) /* line 37 */ {
			echo '            <div class="alert alert-danger">
                <ul>
';
			foreach ($errors as $error) /* line 40 */ {
				echo '                        <li>';
				echo LR\Filters::escapeHtmlText($error) /* line 41 */;
				echo '</li>
';

			}

			echo '                </ul>
            </div>
';
		}
		echo '        
';
		$this->renderBlock('content', [], 'html') /* line 47 */;
		echo '    </main>

    <footer class="bg-light text-center py-4 mt-5">
        <div class="container">
            <p class="mb-0">&copy; ';
		echo LR\Filters::escapeHtmlText(date('Y')) /* line 52 */;
		echo ' Simon og Marvin</p>
        </div>
    </footer>

    <!-- Bootstrap JS Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    
';
		$this->renderBlock('scripts', get_defined_vars()) /* line 59 */;
		echo '</body>
</html>';
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['error' => '40'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}


	/** {block title} on line 6 */
	public function blockTitle(array $ʟ_args): void
	{
		echo 'Søknadsystem for vitenskapelige studenter';
	}


	/** {block styles} on line 11 */
	public function blockStyles(array $ʟ_args): void
	{
	}


	/** {block navigation} on line 25 */
	public function blockNavigation(array $ʟ_args): void
	{
		echo '                        <li class="nav-item">
                            <a class="nav-link" href="/">Home</a>
                        </li>
';
	}


	/** {block scripts} on line 59 */
	public function blockScripts(array $ʟ_args): void
	{
	}
}
