<?php

/** Generated by Latte 3.0.23 */

use Latte\Runtime as LR;

/** source: E:\GitHub\SimonPortillo\soknadsystem_php\app\controllers/../views/positions.latte */
final class Template_d1bd31cbbd extends Latte\Runtime\Template
{
	public const Source = 'E:\\GitHub\\SimonPortillo\\soknadsystem_php\\app\\controllers/../views/positions.latte';

	public const Blocks = [
		['title' => 'blockTitle', 'content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('title', get_defined_vars()) /* line 3 */;
		echo '

';
		$this->renderBlock('content', get_defined_vars()) /* line 5 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		$this->parentName = 'layout.latte';
		return get_defined_vars();
	}


	/** {block title} on line 3 */
	public function blockTitle(array $ʟ_args): void
	{
		echo 'Ledige stillinger';
	}


	/** {block content} on line 5 */
	public function blockContent(array $ʟ_args): void
	{
		echo '<div class="row">
    <div class="col-lg-12">
        <div class="card shadow-sm">
            <div class="card-body text-center py-5">
                <h1 class="display-4 mb-4">Ledige stillinger</h1>
                <div class="table-responsive mt-4">
                    <table class="table table-bordered table-striped">
                        <thead class="thead-dark">
                            <tr>
                                <th>Stilling</th>
                                <th>Avdeling</th>
                                <th>Lokasjon</th>
                                <th>Publisert</th>
                                <th>Søk</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Utvikler</td>
                                <td>IT</td>
                                <td>Oslo</td>
                                <td>2024-06-01</td>
                                <td><a href="#" class="btn btn-primary btn-sm">Søk</a></td>
                            </tr>
                            <tr>
                                <td>Prosjektleder</td>
                                <td>Prosjekt</td>
                                <td>Bergen</td>
                                <td>2024-05-28</td>
                                <td><a href="#" class="btn btn-primary btn-sm">Søk</a></td>
                            </tr>
                            <tr>
                                <td>Designer</td>
                                <td>Markedsføring</td>
                                <td>Trondheim</td>
                                <td>2024-05-20</td>
                                <td><a href="#" class="btn btn-primary btn-sm">Søk</a></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
';
	}
}
