<?php

/** Generated by Latte 3.0.23 */

use Latte\Runtime as LR;

/** source: E:\GitHub\SimonPortillo\soknadsystem_php\app\controllers/../views/home.latte */
final class Template_e5ecda0402 extends Latte\Runtime\Template
{
	public const Source = 'E:\\GitHub\\SimonPortillo\\soknadsystem_php\\app\\controllers/../views/home.latte';

	public const Blocks = [
		['title' => 'blockTitle', 'content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('title', get_defined_vars()) /* line 3 */;
		echo '

';
		$this->renderBlock('content', get_defined_vars()) /* line 5 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		$this->parentName = 'layout.latte';
		return get_defined_vars();
	}


	/** {block title} on line 3 */
	public function blockTitle(array $ʟ_args): void
	{
		echo 'Home - Søknadsystem';
	}


	/** {block content} on line 5 */
	public function blockContent(array $ʟ_args): void
	{
		echo '<div class="row">
    <div class="col-lg-12">
        <div class="card shadow-sm">
            <div class="card-body text-center py-5">
                <h1 class="display-4 mb-4">Søknadsystem for vitenskapelige studenter</h1>
                
                <p class="lead text-muted">
                    Velkommen til vårt søknadsystem for vitenskapelige studenter! Her kan du utforske stillinger og sende inn din søknad.
                </p>
                <button class="btn btn-primary btn-lg mt-3">
                    <a class="text-white" href="/login"> Gå til stillinger </a>
                </button>
            </div>
        </div>
    </div>
</div>
';
	}
}
