<?php

/** Generated by Latte 3.0.23 */

use Latte\Runtime as LR;

/** source: E:\GitHub\SimonPortillo\soknadsystem_php\app\controllers/../views/login.latte */
final class Template_95c62e59ef extends Latte\Runtime\Template
{
	public const Source = 'E:\\GitHub\\SimonPortillo\\soknadsystem_php\\app\\controllers/../views/login.latte';

	public const Blocks = [
		['title' => 'blockTitle', 'content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('title', get_defined_vars()) /* line 3 */;
		echo '

';
		$this->renderBlock('content', get_defined_vars()) /* line 5 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		$this->parentName = 'layout.latte';
		return get_defined_vars();
	}


	/** {block title} on line 3 */
	public function blockTitle(array $ʟ_args): void
	{
		echo 'Login';
	}


	/** {block content} on line 5 */
	public function blockContent(array $ʟ_args): void
	{
		echo '<div class="row justify-content-center">
    <div class="col-md-6 col-lg-4">
        <div class="card shadow-sm mt-5">
            <div class="card-body">
                <h2 class="mb-4 text-center">Login</h2>
                <form method="post" action="/login" novalidate>
                    <div class="mb-3">
                        <label for="username" class="form-label">Brukernavn</label>
                        <input type="text" class="form-control" id="username" name="username" required autocomplete="username">
                    </div>
                    <div class="mb-3">
                        <label for="password" class="form-label">Passord</label>
                        <input type="password" class="form-control" id="password" name="password" required autocomplete="current-password">
                    </div>
                    <button type="submit" class="btn btn-primary w-100">Login</button>
                    <div class="mt-3 text-center">
                        <a href="/register" class="link-secondary">Har du ikke konto? Registrer deg</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
';
	}
}
